version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/New_York
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: chore

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:30"
      timezone: America/New_York
    groups:
      python-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: chore

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
      day: monday
      time: "11:00"
      timezone: America/New_York
    groups:
      docs-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: chore
