"""Hardcoded SO101 menagerie constants for the ManiSkill backend.

All values are sourced from the vendored MuJoCo Menagerie model at
``so101_nexus_core/assets/SO101_menagerie/so101.xml`` and locked by
``tests/test_menagerie_constants.py``. The ManiSkill MJCF importer drops
inertials, gripper friction (condim 6), the TCP site, and joint armature, so
these are restored post-load. See the design doc
``docs/superpowers/specs/2026-06-12-maniskill-menagerie-so101-design.md``.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class LinkInertial:
    """A link's inertial properties in its body frame.

    ``principal_moments`` are the eigenvalues of the MuJoCo ``fullinertia``
    matrix; ``principal_quat`` (w, x, y, z) orients the principal axes relative
    to the link frame. Together they reconstruct the full inertia tensor for
    SAPIEN's ``set_inertia`` + ``set_cmass_local_pose``.
    """

    mass: float
    com_pos: tuple[float, float, float]
    principal_moments: tuple[float, float, float]
    principal_quat: tuple[float, float, float, float]


# Inertials (mass/com/fullinertia transcribed from the XML <inertial> tags;
# principal_moments/principal_quat generated by eigendecomposition, locked by
# test_menagerie_constants.py). Each entry's principal_moments and principal_quat
# share one frame, so set_inertia + set_cmass_local_pose reconstruct the tensor
# regardless of moment ordering. camera_mount is sourced differently (see below).
LINK_INERTIALS: dict[str, LinkInertial] = {
    "base": LinkInertial(
        mass=0.147,
        com_pos=(0.0137179, -5.19711e-05, 0.0334843),
        principal_moments=(0.0001132328432002171, 0.00013180727904032427, 0.00013612687775945865),
        principal_quat=(
            0.6982441491450333,
            -0.7018028965991832,
            0.09196540069752723,
            0.1070988682679165,
        ),
    ),
    "shoulder": LinkInertial(
        mass=0.100006,
        com_pos=(-0.0307604, -1.7e-05, -0.0252713),
        principal_moments=(2.3955239835030667e-05, 8.10388089425997e-05, 8.378355122236957e-05),
        principal_quat=(
            0.700146144262069,
            -0.008279256794529156,
            0.7138758895332378,
            0.010394466076593733,
        ),
    ),
    "upper_arm": LinkInertial(
        mass=0.103,
        com_pos=(-0.089847, -0.008382, 0.018409),
        principal_moments=(3.724505629277975e-05, 0.00014248698340212697, 0.00015087316030509344),
        principal_quat=(
            0.7049950841647412,
            -0.7036319268467828,
            -0.06285315478930986,
            0.06271781053627865,
        ),
    ),
    "lower_arm": LinkInertial(
        mass=0.104,
        com_pos=(-0.09807, 0.0032438, 0.018283),
        principal_moments=(2.8312456912253552e-05, 0.00014530364353121692, 0.00016026169955652946),
        principal_quat=(
            0.7074477559702502,
            -0.706184462176218,
            0.0237086987780335,
            -0.016095824172612423,
        ),
    ),
    "wrist": LinkInertial(
        mass=0.079,
        com_pos=(-0.000103312, -0.0386143, 0.0281156),
        principal_moments=(1.894344344377934e-05, 2.744737720897245e-05, 3.6826479347248204e-05),
        principal_quat=(
            0.6850207627212316,
            0.1796616806807533,
            -0.6827265378379389,
            -0.17986858999728397,
        ),
    ),
    "gripper": LinkInertial(
        mass=0.087,
        com_pos=(0.000214, 0.000245, -0.025187),
        principal_moments=(2.428392179330236e-05, 3.772288516824972e-05, 4.337349303844791e-05),
        principal_quat=(
            0.6783610047939911,
            0.6897845387324604,
            -0.17118166602275675,
            0.18633430848399163,
        ),
    ),
    "moving_jaw_so101_v1": LinkInertial(
        mass=0.012,
        com_pos=(-0.001575, -0.0300244, 0.0192755),
        principal_moments=(1.8652259035967694e-06, 5.290920121455262e-06, 6.63582397494797e-06),
        principal_quat=(
            0.474258810417403,
            0.4914076320007884,
            -0.5089944404557436,
            -0.5239482603635514,
        ),
    ),
    # camera_mount has no <inertial> tag; MuJoCo compiles its inertia from the
    # visual mesh geom (mass=0.012; the two collision boxes are mass=0). These
    # are the mujoco-compiled body_mass/body_ipos/body_inertia/body_iquat values,
    # guarded by test_camera_mount_inertial_matches_compiled_xml (mujoco-gated).
    # principal_moments here follow MuJoCo's body_inertia axis order (not the
    # ascending eigh order of the entries above); this is fine because they are
    # paired with the matching body_iquat orientation.
    "camera_mount": LinkInertial(
        mass=0.012,
        com_pos=(-0.0009316021647151766, 0.05015953175138088, -0.03543815482904921),
        principal_moments=(4.871996346461968e-06, 3.833764238074214e-06, 1.1727282901777604e-06),
        principal_quat=(
            -0.3709944824590795,
            0.6039161056276212,
            -0.5980133440272004,
            -0.3742037836712713,
        ),
    ),
}

# TCP frame: gripperframe site relative to the 'gripper' body (w, x, y, z).
TCP_OFFSET_POS: tuple[float, float, float] = (0.012, -0.000218, -0.098127)
TCP_OFFSET_QUAT: tuple[float, float, float, float] = (0.0, 0.0, 1.0, 0.0)

# Wrist camera: fixed quaternion (w, x, y, z) converting the MuJoCo camera
# optical convention (looks along -z, +y up) to SAPIEN's (looks along +x, +z up,
# +y left, confirmed via sapien_utils.look_at). Applied as
# qmult(q_mujoco_pitch, MJ_TO_SAPIEN_CAMERA_QUAT) so the SAPIEN wrist camera
# matches the MuJoCo backend's. Verified against the MuJoCo backend world optical
# axes in test_wrist_camera_world_pose_matches_mujoco_backend.
MJ_TO_SAPIEN_CAMERA_QUAT: tuple[float, float, float, float] = (0.5, -0.5, 0.5, 0.5)

# Gripper friction (link-level; every collision geom on these bodies has
# MuJoCo sliding mu = 1.0). patch_radius stands in for MuJoCo torsional friction.
GRIPPER_FRICTION_LINKS: tuple[str, str, str] = ("gripper", "moving_jaw_so101_v1", "camera_mount")
GRIPPER_STATIC_FRICTION: float = 1.0
GRIPPER_DYNAMIC_FRICTION: float = 1.0
GRIPPER_PATCH_RADIUS: float = 0.1
GRIPPER_MIN_PATCH_RADIUS: float = 0.1

# STS3215 joint dynamics (sts3215 default class).
JOINT_FRICTIONLOSS: float = 0.052  # Coulomb friction; carried by the controller config.
JOINT_ARMATURE: float = 0.028  # set post-load (loader/controllers never apply it).
PASSIVE_JOINT_DAMPING: float = 0.60
STS3215_KV: float = 2.731
DRIVE_STIFFNESS: float = 998.22
# PhysX has no separate passive viscous damping; the controller drive overwrites
# the loader-imported damping, so passive damping is folded into the drive.
DRIVE_DAMPING: float = STS3215_KV + PASSIVE_JOINT_DAMPING  # 3.331
FORCE_LIMIT: float = 2.94

# Compiled joint limits (radians), from the MJCF <joint range=...>.
JOINT_LIMITS: dict[str, tuple[float, float]] = {
    "shoulder_pan": (-1.91986, 1.91986),
    "shoulder_lift": (-1.7453293, 1.7453293),
    "elbow_flex": (-1.69, 1.69),
    "wrist_flex": (-1.658063, 1.658063),
    "wrist_roll": (-2.7438473, 2.7438473),
    "gripper": (-0.174533, 1.7453292),
}
